spring:
  application:
    name: adg-rule
  profiles:
    active: prod  #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs

application:
  config:
    expected_quantity: 2000000  #预期规则数量
    fault_tolerance: 0.001 #容错率
    warn_limit: 7 #警告阈值, 规则长度小于该值时会输出警告日志
    batch_size: 10000 #写入文件的批次大小

  # 规则源配置，remote为远程规则，local为本地规则，支持多个规则源
  rule:

    # 仅支持 http/https，不限定响应内容格式
    remote:
      - name: AdGuard 基础过滤器
        path: https://filters.adtidy.org/android/filters/2_optimized.txt
      - name: AdGuard 移动广告过滤器
        path: https://filters.adtidy.org/android/filters/11_optimized.txt
      - name: AdGuard URL跟踪过滤器
        path: https://filters.adtidy.org/android/filters/17_optimized.txt
      - name: AdGuard 防跟踪保护过滤器
        path: https://filters.adtidy.org/android/filters/3_optimized.txt
      - name: AdGuard 社交媒体过滤器
        path: https://filters.adtidy.org/android/filters/4_optimized.txt
      - name: AdGuard 恼人广告过滤器
        path: https://filters.adtidy.org/android/filters/14_optimized.txt
      - name: AdGuard 解除搜索广告和自我推销过滤器
        path: https://filters.adtidy.org/android/filters/10_optimized.txt
      - name: AdGuard 中文过滤器
        path: https://filters.adtidy.org/android/filters/224_optimized.txt
      - name: CJX's Annoyance List
        path: https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt
      - name: 乘风 广告过滤规则
        path: https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/rule.txt
      - name: 乘风 视频过滤规则
        path: https://cdn.jsdelivr.net/gh/sbwml/halflife-list@master/ad.txt
      - name: AWAvenue 秋风广告规则
        path: https://ghproxy.net/https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Adblock-Rule/main/AWAvenue-Adblock-Rule.txt
      - name: OISD Big
        path: https://big.oisd.nl
      - name: jiekouAD
        path: https://raw.githubusercontent.com/damengzhu/banad/main/jiekouAD.txt
      - name: AakList (Anti-Adblock Killer)
        path: https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt
      - name: ABP filters
        path: https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt
      - name: ClearURLs for uBo (unofficial)
        path: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt
      - name: uBlock₀ filters – Privacy
        path: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/privacy.txt
        
        

    #本地规则请将文件放置到项目路径rule目录中
    local:
#      - name: 'local rule'
#        path: 'local-rule.txt'
  output:
    file_header: |  #输出文件头, 占位符${name}将被替换为文件名，如all.txt,  ${date} 将被替换为当前日期
      [ADFS Adblock List]
      ! Title: ${name}
      ! Last Modified: ${date}
      ! Homepage: https://github.com/fordes123/ad-filters-subscriber/
    path: rule   #规则文件输出路径，相对路径默认从 项目目录开始
    files:
      all.txt: #输出文件名
        - DOMAIN  #域名规则，仅完整域名
        - REGEX   #正则规则，包含正则的域名规则，AdGH支持
        - MODIFY  #修饰规则，添加了一些修饰符号的规则，AdG支持
        - HOSTS   #Hosts规则
      dns.txt:
        - DOMAIN
        - REGEX
        - HOSTS
      hosts.txt:
        - HOSTS
      regex.txt:
        - REGEX
      domain.txt:
        - DOMAIN
      modify.txt:
        - MODIFY
